name: Metrics
on:
  # Update metrics daily
  schedule:
    - cron: "0 0 * * *"

  # Run workflow manually
  workflow_dispatch:

  # Run workflow when pushing to main
  push:
    branches:
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.19
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, community, repositories

          plugin_languages:           yes
          plugin_languages_threshold: 2%
          plugin_languages_limit:     8

          plugin_habits:        yes
          plugin_habits_from:   800
          plugin_habits_days:   28
          plugin_habits_charts: yes

          plugin_achievements:         yes
          plugin_achievements_display: compact

# yaml-language-server: https://json.schemastore.org/github-workflow.json
